;;;; chicken.io.import.scm - GENERATED BY CHICKEN 6.0.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'chicken.io
      'library
      (scheme#list)
      '((read-list . chicken.io#read-list)
        (read-buffered . chicken.io#read-buffered)
        (read-byte . chicken.io#read-byte)
        (read-line . chicken.io#read-line)
        (read-lines . chicken.io#read-lines)
        (read-string . chicken.io#read-string)
        (read-string! . chicken.io#read-string!)
        (read-token . chicken.io#read-token)
        (write-byte . chicken.io#write-byte)
        (write-line . chicken.io#write-line)
        (write-bytevector . chicken.io#write-bytevector)
        (read-bytevector . chicken.io#read-bytevector)
        (read-bytevector! . chicken.io#read-bytevector!))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
