;;;; chicken.version.import.scm - GENERATED BY CHICKEN 6.0.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'chicken.version
      'extras
      (scheme#list)
      '((version>=? . chicken.version#version>=?))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
