;;;; chicken.number-vector.import.scm - GENERATED BY CHICKEN 6.0.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'chicken.number-vector
      'srfi-4
      (scheme#list)
      '((bytevector->f32vector . chicken.number-vector#bytevector->f32vector)
        (bytevector->f32vector/shared
          .
          chicken.number-vector#bytevector->f32vector/shared)
        (bytevector->f64vector . chicken.number-vector#bytevector->f64vector)
        (bytevector->f64vector/shared
          .
          chicken.number-vector#bytevector->f64vector/shared)
        (bytevector->s16vector . chicken.number-vector#bytevector->s16vector)
        (bytevector->s16vector/shared
          .
          chicken.number-vector#bytevector->s16vector/shared)
        (bytevector->s32vector . chicken.number-vector#bytevector->s32vector)
        (bytevector->s32vector/shared
          .
          chicken.number-vector#bytevector->s32vector/shared)
        (bytevector->s64vector . chicken.number-vector#bytevector->s64vector)
        (bytevector->s64vector/shared
          .
          chicken.number-vector#bytevector->s64vector/shared)
        (bytevector->s8vector . chicken.number-vector#bytevector->s8vector)
        (bytevector->s8vector/shared
          .
          chicken.number-vector#bytevector->s8vector/shared)
        (bytevector->u16vector . chicken.number-vector#bytevector->u16vector)
        (bytevector->u16vector/shared
          .
          chicken.number-vector#bytevector->u16vector/shared)
        (bytevector->u32vector . chicken.number-vector#bytevector->u32vector)
        (bytevector->u32vector/shared
          .
          chicken.number-vector#bytevector->u32vector/shared)
        (bytevector->u64vector . chicken.number-vector#bytevector->u64vector)
        (bytevector->u64vector/shared
          .
          chicken.number-vector#bytevector->u64vector/shared)
        (bytevector->c64vector . chicken.number-vector#bytevector->c64vector)
        (bytevector->c64vector/shared
          .
          chicken.number-vector#bytevector->c64vector/shared)
        (bytevector->c128vector . chicken.number-vector#bytevector->c128vector)
        (bytevector->c128vector/shared
          .
          chicken.number-vector#bytevector->c128vector/shared)
        (f32vector . chicken.number-vector#f32vector)
        (f32vector->bytevector . chicken.number-vector#f32vector->bytevector)
        (f32vector->bytevector/shared
          .
          chicken.number-vector#f32vector->bytevector/shared)
        (f32vector->list . chicken.number-vector#f32vector->list)
        (f32vector-length . chicken.number-vector#f32vector-length)
        (f32vector-ref . chicken.number-vector#f32vector-ref)
        (f32vector-set! . chicken.number-vector#f32vector-set!)
        (f32vector? . chicken.number-vector#f32vector?)
        (f64vector . chicken.number-vector#f64vector)
        (f64vector->bytevector . chicken.number-vector#f64vector->bytevector)
        (f64vector->bytevector/shared
          .
          chicken.number-vector#f64vector->bytevector/shared)
        (f64vector->list . chicken.number-vector#f64vector->list)
        (f64vector-length . chicken.number-vector#f64vector-length)
        (f64vector-ref . chicken.number-vector#f64vector-ref)
        (f64vector-set! . chicken.number-vector#f64vector-set!)
        (f64vector? . chicken.number-vector#f64vector?)
        (s8vector . chicken.number-vector#s8vector)
        (s8vector->bytevector . chicken.number-vector#s8vector->bytevector)
        (s8vector->bytevector/shared
          .
          chicken.number-vector#s8vector->bytevector/shared)
        (s8vector->list . chicken.number-vector#s8vector->list)
        (s8vector-length . chicken.number-vector#s8vector-length)
        (s8vector-ref . chicken.number-vector#s8vector-ref)
        (s8vector-set! . chicken.number-vector#s8vector-set!)
        (s8vector? . chicken.number-vector#s8vector?)
        (s16vector . chicken.number-vector#s16vector)
        (s16vector->bytevector . chicken.number-vector#s16vector->bytevector)
        (s16vector->bytevector/shared
          .
          chicken.number-vector#s16vector->bytevector/shared)
        (s16vector->list . chicken.number-vector#s16vector->list)
        (s16vector-length . chicken.number-vector#s16vector-length)
        (s16vector-ref . chicken.number-vector#s16vector-ref)
        (s16vector-set! . chicken.number-vector#s16vector-set!)
        (s16vector? . chicken.number-vector#s16vector?)
        (s32vector . chicken.number-vector#s32vector)
        (s32vector->bytevector . chicken.number-vector#s32vector->bytevector)
        (s32vector->bytevector/shared
          .
          chicken.number-vector#s32vector->bytevector/shared)
        (s32vector->list . chicken.number-vector#s32vector->list)
        (s32vector-length . chicken.number-vector#s32vector-length)
        (s32vector-ref . chicken.number-vector#s32vector-ref)
        (s32vector-set! . chicken.number-vector#s32vector-set!)
        (s32vector? . chicken.number-vector#s32vector?)
        (s64vector . chicken.number-vector#s64vector)
        (s64vector->bytevector . chicken.number-vector#s64vector->bytevector)
        (s64vector->bytevector/shared
          .
          chicken.number-vector#s64vector->bytevector/shared)
        (s64vector->list . chicken.number-vector#s64vector->list)
        (s64vector-length . chicken.number-vector#s64vector-length)
        (s64vector-ref . chicken.number-vector#s64vector-ref)
        (s64vector-set! . chicken.number-vector#s64vector-set!)
        (s64vector? . chicken.number-vector#s64vector?)
        (u8vector . chicken.number-vector#u8vector)
        (u8vector->list . chicken.number-vector#u8vector->list)
        (u8vector-length . chicken.number-vector#u8vector-length)
        (u8vector-ref . chicken.number-vector#u8vector-ref)
        (u8vector-set! . chicken.number-vector#u8vector-set!)
        (u8vector? . chicken.number-vector#u8vector?)
        (u16vector . chicken.number-vector#u16vector)
        (u16vector->bytevector . chicken.number-vector#u16vector->bytevector)
        (u16vector->bytevector/shared
          .
          chicken.number-vector#u16vector->bytevector/shared)
        (u16vector->list . chicken.number-vector#u16vector->list)
        (u16vector-length . chicken.number-vector#u16vector-length)
        (u16vector-ref . chicken.number-vector#u16vector-ref)
        (u16vector-set! . chicken.number-vector#u16vector-set!)
        (u16vector? . chicken.number-vector#u16vector?)
        (u32vector . chicken.number-vector#u32vector)
        (u32vector->bytevector . chicken.number-vector#u32vector->bytevector)
        (u32vector->bytevector/shared
          .
          chicken.number-vector#u32vector->bytevector/shared)
        (u32vector->list . chicken.number-vector#u32vector->list)
        (u32vector-length . chicken.number-vector#u32vector-length)
        (u32vector-ref . chicken.number-vector#u32vector-ref)
        (u32vector-set! . chicken.number-vector#u32vector-set!)
        (u32vector? . chicken.number-vector#u32vector?)
        (u64vector . chicken.number-vector#u64vector)
        (u64vector->bytevector . chicken.number-vector#u64vector->bytevector)
        (u64vector->bytevector/shared
          .
          chicken.number-vector#u64vector->bytevector/shared)
        (u64vector->list . chicken.number-vector#u64vector->list)
        (u64vector-length . chicken.number-vector#u64vector-length)
        (u64vector-ref . chicken.number-vector#u64vector-ref)
        (u64vector-set! . chicken.number-vector#u64vector-set!)
        (u64vector? . chicken.number-vector#u64vector?)
        (c64vector . chicken.number-vector#c64vector)
        (c64vector->bytevector . chicken.number-vector#c64vector->bytevector)
        (c64vector->bytevector/shared
          .
          chicken.number-vector#c64vector->bytevector/shared)
        (c64vector->list . chicken.number-vector#c64vector->list)
        (c64vector-length . chicken.number-vector#c64vector-length)
        (c64vector-ref . chicken.number-vector#c64vector-ref)
        (c64vector-set! . chicken.number-vector#c64vector-set!)
        (c64vector? . chicken.number-vector#c64vector?)
        (c128vector . chicken.number-vector#c128vector)
        (c128vector->bytevector . chicken.number-vector#c128vector->bytevector)
        (c128vector->bytevector/shared
          .
          chicken.number-vector#c128vector->bytevector/shared)
        (c128vector->list . chicken.number-vector#c128vector->list)
        (c128vector-length . chicken.number-vector#c128vector-length)
        (c128vector-ref . chicken.number-vector#c128vector-ref)
        (c128vector-set! . chicken.number-vector#c128vector-set!)
        (c128vector? . chicken.number-vector#c128vector?)
        (list->f32vector . chicken.number-vector#list->f32vector)
        (list->f64vector . chicken.number-vector#list->f64vector)
        (list->s16vector . chicken.number-vector#list->s16vector)
        (list->s32vector . chicken.number-vector#list->s32vector)
        (list->s64vector . chicken.number-vector#list->s64vector)
        (list->s8vector . chicken.number-vector#list->s8vector)
        (list->u16vector . chicken.number-vector#list->u16vector)
        (list->u32vector . chicken.number-vector#list->u32vector)
        (list->u8vector . chicken.number-vector#list->u8vector)
        (list->u64vector . chicken.number-vector#list->u64vector)
        (list->c64vector . chicken.number-vector#list->c64vector)
        (list->c128vector . chicken.number-vector#list->c128vector)
        (make-f32vector . chicken.number-vector#make-f32vector)
        (make-f64vector . chicken.number-vector#make-f64vector)
        (make-s16vector . chicken.number-vector#make-s16vector)
        (make-s32vector . chicken.number-vector#make-s32vector)
        (make-s64vector . chicken.number-vector#make-s64vector)
        (make-s8vector . chicken.number-vector#make-s8vector)
        (make-u16vector . chicken.number-vector#make-u16vector)
        (make-u32vector . chicken.number-vector#make-u32vector)
        (make-u64vector . chicken.number-vector#make-u64vector)
        (make-u8vector . chicken.number-vector#make-u8vector)
        (make-c64vector . chicken.number-vector#make-c64vector)
        (make-c128vector . chicken.number-vector#make-c128vector)
        (number-vector? . chicken.number-vector#number-vector?)
        (release-number-vector . chicken.number-vector#release-number-vector)
        (subf32vector . chicken.number-vector#subf32vector)
        (subf64vector . chicken.number-vector#subf64vector)
        (subs16vector . chicken.number-vector#subs16vector)
        (subs32vector . chicken.number-vector#subs32vector)
        (subs64vector . chicken.number-vector#subs64vector)
        (subs8vector . chicken.number-vector#subs8vector)
        (subu16vector . chicken.number-vector#subu16vector)
        (subu8vector . chicken.number-vector#subu8vector)
        (subu32vector . chicken.number-vector#subu32vector)
        (subu64vector . chicken.number-vector#subu64vector)
        (subc64vector . chicken.number-vector#subc64vector)
        (subc128vector . chicken.number-vector#subc128vector))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
