;;;; chicken.bytevector.import.scm - GENERATED BY CHICKEN 6.0.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'chicken.bytevector
      'library
      (scheme#list)
      '((bytevector? . chicken.bytevector#bytevector?)
        (bytevector=? . chicken.bytevector#bytevector=?)
        (bytevector-length . chicken.bytevector#bytevector-length)
        (make-bytevector . chicken.bytevector#make-bytevector)
        (bytevector . chicken.bytevector#bytevector)
        (bytevector-u8-ref . chicken.bytevector#bytevector-u8-ref)
        (bytevector-u8-set! . chicken.bytevector#bytevector-u8-set!)
        (bytevector-copy . chicken.bytevector#bytevector-copy)
        (bytevector-copy! . chicken.bytevector#bytevector-copy!)
        (bytevector-append . chicken.bytevector#bytevector-append)
        (utf8->string . chicken.bytevector#utf8->string)
        (string->utf8 . chicken.bytevector#string->utf8)
        (latin1->string . chicken.bytevector#latin1->string)
        (string->latin1 . chicken.bytevector#string->latin1)
        (bytes->string . chicken.bytevector#bytes->string))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
