;;;; scheme.file.import.scm - GENERATED BY CHICKEN 6.0.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'scheme.file
      'r7lib
      (scheme#list)
      '((file-exists? . scheme.file#file-exists?)
        (delete-file . chicken.file#delete-file)
        (open-input-file . scheme#open-input-file)
        (open-binary-input-file . scheme.file#open-binary-input-file)
        (open-output-file . scheme#open-output-file)
        (open-binary-output-file . scheme.file#open-binary-output-file)
        (call-with-input-file . scheme#call-with-input-file)
        (call-with-output-file . scheme#call-with-output-file)
        (with-input-from-file . scheme#with-input-from-file)
        (with-output-to-file . scheme#with-output-to-file))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
