;;;; scheme.write.import.scm - GENERATED BY CHICKEN 6.0.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'scheme.write
      'r7lib
      (scheme#list)
      '((display . scheme.write#display)
        (write . scheme.write#write)
        (write-shared . scheme.write#write-shared)
        (write-simple . scheme#write))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
