;;;; scheme.process-context.import.scm - GENERATED BY CHICKEN 6.0.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'scheme.process-context
      'r7lib
      (scheme#list)
      '((command-line . scheme.process-context#command-line)
        (emergency-exit . chicken.base#emergency-exit)
        (exit . scheme.process-context#exit)
        (get-environment-variable
          .
          chicken.process-context#get-environment-variable)
        (get-environment-variables
          .
          chicken.process-context#get-environment-variables))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
