;;;; scheme.time.import.scm - GENERATED BY CHICKEN 6.0.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'scheme.time
      'r7lib
      (scheme#list)
      '((current-second . scheme.time#current-second)
        (current-jiffy . scheme.time#current-jiffy)
        (jiffies-per-second . scheme.time#jiffies-per-second))
      (scheme#list)
      (scheme#list)
      (scheme#list))))

;; END OF FILE
